/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_jh_lim_FourierTest_Main */

#ifndef _Included_com_jh_lim_FourierTest_Main
#define _Included_com_jh_lim_FourierTest_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jh_lim_FourierTest_Main
 * Method:    testFourier
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_com_jh_1lim_FourierTest_Main_testFourier
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
